services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    environment:
      - 'MONGO_INITDB_DATABASE=bookstore'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'

    ports:
      - "27020:27017"



